### ISSUE TITLE
Missing Icons in the repo

### ISSUE THREAD

**Issue by ai-hemant** [dataloop-ai/icons#1]
Please add the following icons to the repo:

- forward_5
- replay_5

The look of these icons is shown in the following image:

<img width="1245" alt="Screenshot 2023-03-06 at 1 13 12 PM" src="https://user-images.githubusercontent.com/125646532/223975163-aecda2b4-8495-49c5-8b86-1783835d6735.png">

**Comment by fadiDL** [comment]
@ai-hemant These icons exist under the names 
`icon-dl-sec-back`
and 
`icon-dl-sec-back`

@rotemshaham did a rename of certain icons recently.
